"""
KernossAI Core - Servicios centrales de configuración, autenticación, i18n, TTS y diseño.
"""

from KernossAI.core.theme import (
    VERSION_APP,
    COLOR_BG_DARK,
    COLOR_BG_SIDEBAR,
    COLOR_BG_CARD,
    COLOR_BG_CARD_LIGHT,
    COLOR_BG_SURFACE,
    COLOR_BORDER,
    COLOR_BORDER_GLOW,
    COLOR_ACCENT_PRIMARY,
    COLOR_ACCENT_HOVER,
    COLOR_ACCENT_CYAN,
    COLOR_ACCENT_CYAN_HOVER,
    COLOR_ACCENT_SKY,
    COLOR_ACCENT_PURPLE,
    COLOR_ACCENT_PURPLE_HOVER,
    COLOR_TEXT_MAIN,
    COLOR_TEXT_MUTED,
    COLOR_TEXT_DIM,
    COLOR_SUCCESS,
    COLOR_SUCCESS_HOVER,
    COLOR_WARNING,
    COLOR_DANGER,
    COLOR_DANGER_HOVER,
    centrar_ventana,
    aplicar_icono,
    es_version_superior,
    construir_prompt,
)

from KernossAI.core.config import (
    inicializar_config,
    guardar_keys,
    obtener_keys,
    guardar_ajustes_tts,
    obtener_ajustes_tts,
    guardar_idioma,
    obtener_idioma,
    obtener_fecha_instalacion,
    obtener_pase_temporal,
    guardar_activacion_pase_temporal,
)

from KernossAI.core.i18n import (
    t,
    fijar_idioma,
    IDIOMAS_DISPONIBLES,
    obtener_idioma_activo,
)

from KernossAI.core.auth import (
    login,
    registro,
    llamar_gemini,
    llamar_groq,
    consultar_ia,
    token_guardado,
    borrar_token,
    actualizar_hogar_principal,
    borrar_cuenta_usuario,
    obtener_chats_cloud,
    guardar_chat_cloud,
    borrar_chat_cloud,
    enviar_mensaje_soporte,
    obtener_mensajes_soporte,
    admin_listar_usuarios,
    admin_aplicar_ban,
    admin_desbanear,
    admin_ver_mensajes_raw,
    admin_eliminar_usuario,
    admin_obtener_tickets_soporte,
    admin_responder_ticket_soporte,
    obtener_cuentas_guardadas,
    cambiar_a_cuenta,
    eliminar_cuenta_switcher,
    agregar_cuenta_secundaria,
    actualizar_rol_usuario,
    verificar_estado_baneo,
    admin_borrar_ticket_soporte,
    tutoria_listar_profesores,
    tutoria_enviar_solicitud,
    tutoria_obtener_estado_alumno,
    tutoria_profesor_obtener_solicitudes_y_alumnos,
    tutoria_profesor_responder_solicitud,
    tutoria_enviar_mensaje,
    tutoria_obtener_mensajes_chat,
    tutoria_desvincular,
    obtener_estado_casa,
    fijar_red_hogar_actual,
    activar_pase_hogar_temporal,
    limpiar_respuesta_ia,
)

from KernossAI.core.tts import (
    tts_engine,
    VOICES_DISPONIBLES,
    VELOCIDADES_DISPONIBLES,
    limpiar_texto_para_tts,
)
